### PR TITLE
ci: Move clippy to a code scanning action

### PR DESCRIPTION
**Pull request by dave-tucker**
There's support for clippy -> sarif and therefore integration into the GitHub Code Scanning infrastructure. Let's try this out.

### CODE REVIEW

**Comment by Billy99** [comment]
Just a couple of questions/notes:
* What additional functionality is this providing? I looked up clippy-sarif and it converts to output to SARIF to be uploaded to github. But how is that going to be leveraged in github? Are clippy errors just shown in the code now?
* If we decide we want it, we need to update the CONTRIBUTING.md to show how to run locally ([here](https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md?plain=1#L181)) when an error is encountered. `cargo +nightly clippy --all -- --deny warnings` should have been there currently but it wasn't.
* Update docs [here](https://github.com/bpfman/bpfman/blob/main/docs/getting-started/building-bpfman.md?plain=1#L78) for new packages that are needed to run locally.

**Comment by anfredette** [comment]
I was just looking into this too:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/about-integration-with-code-scanning

**Comment by anfredette** [comment]
I was also wondering what we get this this change.  The results are uploaded and then can be used by other tools, but I'm not sure which ones we would use.  Maybe errors will show up in the code review tool?

> Are clippy errors just shown in the code now?

I think rust-analyzer shows us most of the errors in vscode now, but it's not exactly the same as when you run `cargo +nightly clippy --all -- --deny warnings`.

I'll wait for Dave's response.

**Comment by dave-tucker** [comment]
> What additional functionality is this providing? I looked up clippy-sarif and it converts to output to SARIF to be uploaded to github. But how is that going to be leveraged in github? Are clippy errors just shown in the code now?

This should make clippy run as a code scanning tool - so any alerts will also show up here - alongside any other code scanning tools we might add:
https://github.com/bpfman/bpfman/security/code-scanning

I also hope it can give a better experience. i.e it should show the lines that violate the clippy rule in the UI.

> If we decide we want it, we need to update the CONTRIBUTING.md to show how to run locally ([here](https://github.com/bpfman/bpfman/blob/main/CONTRIBUTING.md?plain=1#L181)) when an error is encountered. cargo +nightly clippy --all -- --deny warnings should have been there currently but it wasn't.

I'll open an issue about using [precommit](https://pre-commit.com/) as it can automate all these pre-commit checks.
Then we'll have less docs to update 😄 

> Update docs [here](https://github.com/bpfman/bpfman/blob/main/docs/getting-started/building-bpfman.md?plain=1#L78) for new packages that are needed to run locally.

No changes required as no new packages required.

I think it's worth trying out and if we hate it, we can back it out again.

**Review by anfredette — COMMENTED** [review]
LGTM.  Let's give it a try.

@Billy99, I'll leave it to you to approve.

**Review by Billy99 — APPROVED** [review]
/lgtm

Now that the release is out, let give it a try.

**Pull request merged**
