### PR TITLE
cut release 0.5.0-rc1

### PR DESCRIPTION
**Pull request by anfredette**
write changelog, bump necessary versions.

### CODE REVIEW

**Review by msherif1234 — APPROVED** [review]

**Comment by msherif1234** [comment]
there should be a new folder created here https://github.com/bpfman/bpfman/tree/main/examples/config for `v0.5.0` ?

**Comment by anfredette** [comment]
> there should be a new folder created here https://github.com/bpfman/bpfman/tree/main/examples/config for `v0.5.0` ? or that will be created post merge ?

I think @astoycos said to do that as part of the actual release (non-rc) pr.

**Review by astoycos — APPROVED** [review]
LGTM

**Pull request merged**
